import { Ability, Skill, Status } from '../interfaces';
import { gunbreakerActionNames,  gunbreakerDotNames, gunbreakerStatusNames } from './enums';

export const gunbreakerSkills: Skill[] = [
    {
        cd: 2.4,
        comboActions: [gunbreakerActionNames.BRUTAL_SHELL],
        description: '<h4>Keen Edge</h4><p></p>Delivers an attack with a potency of 200',
        isUsable: true,
        name: gunbreakerActionNames.KEEN_EDGE,
        potency: 200,
        recast: 2.400,
        recastShared: true,
    },
    {
        cd: 2.400,
        comboActions: [gunbreakerActionNames.SOLID_BARREL],
        comboPotency: 300,
        description: '<h4>Brutal Shell</h4><p></p>Delivers an attack with a potency of 100.<p></p><span style="color:green;">Combo Action:</span> <span style="color:orange;">Keen Edge</span><p></p><span style="color:green;">Combo Potency:</span> 300',
        isUsable: true,
        name: gunbreakerActionNames.BRUTAL_SHELL,
        potency: 100,
        recast: 2.400,
        recastShared: true,
    },
    {
        cd: 2.400,
        comboPotency: 400,
        description: '<h4>Solid Barrel</h4><p></p>Delivers an attack with a potency of 100.<p></p>Combo Action: Brutal Shell<p></p>Combo Potency: 400<p></p>Combo Bonus: Adds a Cartridge to your Powder Gauge',
        isUsable: true,
        name: gunbreakerActionNames.SOLID_BARREL,
        potency: 100,
        recast: 2.400,
        recastShared: true,
    },
    {
        cd: 33.630,
        comboActions: [gunbreakerActionNames.SAVAGE_CLAW],
        description: '<h4>Gnashing Fang</h4><p></p>Delivers an attack with a potency of 400<p></p>Additional Effect: Grants Ready to Rip<p></p>Duration: 10s<p></p>Cartridge Cost: 1<p></p>This weaponskill does not share a recast timer with any other actions.',
        isUsable: true,
        name: gunbreakerActionNames.GNASHING_FANG,
        potency: 400,
        recast: 33.630,
        recastShared: false,
    },
    {
        cd: 2.400,
        comboActions: [gunbreakerActionNames.WICKED_TALON],
        description: '<h4>Savage Claw</h4><p></p>Delivers an attack with a potency of 500.<p></p>Combo Action: Gnashing Fang<p></p>Additional Effect: Grants Ready to Tear<p></p>Duration: 10s<p></p>Requires a successful combo to receive the additional effect.',
        isUsable: true,
        name: gunbreakerActionNames.SAVAGE_CLAW,
        potency: 500,
        recast: 2.400,
        recastShared: true,
    },
    {
        cd: 2.400,
        description: '<h4>Wicked Talon</h4><p></p>Delivers an attack with a potency of 650.<p></p>Combo Action: Savage Claw<p></p>Additional Effect: Grants Ready to Gouge<p></p>Duration: 10s<p></p>Requires a successful combo to receive the additional effect.',
        isUsable: true,
        name: gunbreakerActionNames.WICKED_TALON,
        potency: 650,
        recast: 2.400,
        recastShared: true,
    },
    {
        cd: 2.400,
        description: '<h4>Burst Strike</h4><p></p>Delivers an attack with a potency of 450.<p></p>Cartridge Cost: 1',
        isUsable: true,
        name: gunbreakerActionNames.BURST_STRIKE,
        potency: 450,
        recast: 2.400,
        recastShared: true,
    },
    {
        cd: 2.400,
        comboActions: [gunbreakerActionNames.DEMON_SLAUGHTER],
        description: '<h4>Demon Slice</h4><p></p>Delivers an attack with a potency of 150 to all nearby enemies.',
        isAoe: true,
        isUsable: true,
        name: gunbreakerActionNames.DEMON_SLICE,
        potency: 150,
        recast: 2.400,
        recastShared: true,
    },
    {
        cd: 2.400,
        comboPotency: 250,
        description: '<h4>Demon Slaughter</h4><p></p>Delivers an attack with a potency of 100 to all nearby enemies.<p></p>Combo Action: Demon Slice<p></p>Combo Potency: 250<p></p>Combo Bonus: Adds a Cartridge to your Powder Gauge',
        isAoe: true,
        isUsable: true,
        name: gunbreakerActionNames.DEMON_SLAUGHTER,
        potency: 100,
        recast: 2.400,
        recastShared: true,
    },
    {
        cd: 2.400,
        description: '<h4>Lightning Shot</h4><p></p>Delivers a ranged attack with a potency of 150.',
        isUsable: true,
        name: gunbreakerActionNames.LIGHTNING_SHOT,
        potency: 150,
        recast: 2.400,
        recastShared: true,
    },
    {
        cd: 28.830,
        description: '<h4>Sonic Break</h4><p></p>Delivers an attack with a potency of 100.<p></p>Additional Effect: Damage over time<p></p>Potency: 50<p></p>Duration: 15s<p></p>This weaponskill does not share a recast timer with any other actions.',
        isUsable: true,
        name: gunbreakerActionNames.SONIC_BREAK,
        potency: 100,
        recast: 28.830,
        recastShared: false,
    },
    {
        cd: 2.400,
        description: '<h4>Fated Circle</h4><p></p>Delivers an attack with a potency of 360 to all nearby enemies.<p></p>Cartridge Cost: 1',
        isAoe: true,
        isUsable: true,
        name: gunbreakerActionNames.FATED_CIRCLE,
        potency: 360,
        recast: 2.400,
        recastShared: true,
    },
];

export const gunbreakerAbilities: Ability[] = [
    {
        cd: 60.000,
        currentCharges: 1,
        description: '<h4>No Mercy</h4><p></p>Increases damage dealt by 10%.<p></p>Duration: 20s',
        isUsable: true,
        isVisible: true,
        maxCharges: 1,
        name: gunbreakerActionNames.NO_MERCY,
        recast: 60.000,
    },
    {
        cd: 15.000,
        currentCharges: 2,
        description: '<h4>Rough Divide</h4><p></p>Delivers a jumping attack with a potency of 200.<p></p>Maximum Charges: 2*<p></p>*To make up for lack of charges, cooldown has been reduced by 50% to 15s',
        isUsable: true,
        isVisible: true,
        maxCharges: 2,
        name: gunbreakerActionNames.ROUGH_DIVIDE,
        potency: 200,
        recast: 15.000,
    },
    {
        cd: 60,
        currentCharges: 1,
        description: '<h4>Bow Shock</h4><p></p>Delivers an attack with a potency of 200 to all nearby enemies.<p></p>Additional Effect: Damage over time<p></p>Potency: 90<p></p>Duration: 15s',
        isAoe: true,
        isUsable: true,
        isVisible: true,
        maxCharges: 1,
        name: gunbreakerActionNames.BOW_SHOCK,
        potency: 200,
        recast: 60.000,
    },
    {
        cd: 1.000,
        description: '<h4>Continuation</h4><p></p>Allows the firing of successive rounds with your gunblade.<p></p>Gnashing Fang may be followed by Jugular Rip.<p></p>Savage Claw may be followed by Abdomen Tear.<p></p>Wicked Talon may be followed by Eye Gouge',
        isUsable: true,
        isVisible: true,
        maxCharges: 1,
        name: gunbreakerActionNames.CONTINUATION,
        recast: 1.000,
    },
    {
        cd: 90.000,
        currentCharges: 1,
        description: '<h4>Bloodfest</h4><p></p>Adds 2 Cartridges to your Powder Gauge<p></p>Can only be executed while in combat.',
        isUsable: true,
        isVisible: true,
        maxCharges: 1,
        name: gunbreakerActionNames.BLOODFEST,
        recast: 90.000,
    },
    {
        cd: 30.000,
        currentCharges: 1,
        description: '<h4>Blasting Zone</h4><p></p>Delivers an attack with a potency of 700.',
        isUsable: true,
        isVisible: true,
        maxCharges: 1,
        name: gunbreakerActionNames.BLASTING_ZONE,
        potency: 700,
        recast: 30.000,
    },
    {
        cd: 0,
        description: '<h4>Jugular Rip</h4><p></p>Delivers an attack with a potency of 160.<p></p>Can only be executed when Ready to Tear.',
        isUsable: true,
        isVisible: false,
        maxCharges: 1,
        name: gunbreakerActionNames.JUGULAR_RIP,
        potency: 160,
        recast: 0,
    },
    {
        cd: 0,
        description: '<h4>Abdomen Tear</h4><p></p>Delivers an attack with a potency of 180.<p></p>Can only be executed when Ready to Tear.',
        isUsable: true,
        isVisible: false,
        maxCharges: 1,
        name: gunbreakerActionNames.ABDOMEN_TEAR,
        potency: 180,
        recast: 0,
    },
    {
        cd: 0,
        description: '<h4>Eye Gouge</h4><p></p>Delivers an attack with a potency of 200.<p></p>Can only be executed when Ready to Gouge.',
        isUsable: true,
        isVisible: false,
        maxCharges: 1,
        name: gunbreakerActionNames.EYE_GOUGE,
        potency: 200,
        recast: 0,
    },
];

export const gunbreakerStatuses: Status[] = [
    {
        description: 'Increasing damage by 10%',
        duration: 20000,
        isDot: false,
        name: gunbreakerStatusNames.NO_MERCY,
    },
    {
        description: 'Jugular Rip is available',
        duration: 10000,
        isDot: false,
        name: gunbreakerStatusNames.READY_TO_RIP,
    },
    {
        description: 'Abdomen Tear is available',
        duration: 10000,
        isDot: false,
        name: gunbreakerStatusNames.READY_TO_TEAR,
    },
    {
        description: 'Eye Gouge is available',
        duration: 10000,
        isDot: false,
        name: gunbreakerStatusNames.READY_TO_GOUGE,
    },
    {
        description: 'Dealing damage over time',
        duration: 15000,
        isDot: true,
        name: gunbreakerDotNames.SONIC_BREAK,
        potency: 50,
    },
    {
        description: 'Deaing damage over time',
        duration: 15000,
        isDot: true,
        name: gunbreakerDotNames.BOW_SHOCK,
        potency: 90,
    },
];

export const playerStatuses: Status[] = [
    {
        description: 'Increasing damage by 10%',
        duration: 20000,
        isDot: false,
        name: gunbreakerStatusNames.NO_MERCY,
    },
    {
        description: 'Jugular Rip is available',
        duration: 10000,
        isDot: false,
        name: gunbreakerStatusNames.READY_TO_RIP,
    },
    {
        description: 'Abdomen Tear is available',
        duration: 10000,
        isDot: false,
        name: gunbreakerStatusNames.READY_TO_TEAR,
    },
    {
        description: 'Eye Gouge is available',
        duration: 10000,
        isDot: false,
        name: gunbreakerStatusNames.READY_TO_GOUGE,
    },
]

export const enemyDots: Status[] = [
    {
        description: 'Dealing damage over time',
        duration: 15000,
        isDot: true,
        name: gunbreakerDotNames.SONIC_BREAK,
        potency: 50,
    },
    {
        description: 'Deaing damage over time',
        duration: 15000,
        isDot: true,
        name: gunbreakerDotNames.BOW_SHOCK,
        potency: 90,
    },
]
